using Godot;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TerrainGeneration.Application.SDFGenerator;
using TerrainGeneration.Application.SDFGenerator.Abstractions;
using TerrainGeneration.Application.SDFGenerator.Pipeline;
using TerrainGeneration.Application.SDFGenerator.SimplexNoise;
using TerrainGeneration.Application.TerrainGenerator.Transvoxel.NormalsShader;

namespace TerrainGeneration.Application.TerrainGenerator.Transvoxel;
public class TransvoxelTerrainGenerator
{
    RenderingDevice Rd;

    SDFPipeline SdfPipeline;

    NormalsShader.NormalsShader NormalsShader;

    Transvoxel Transvoxel;

    float BorderWidth;
    uint MaxNumVertices;



    /// <summary>
    /// Creates a Transvoxel Terrain Generator instance. This uses the transvoxel meshing algorithm.
    /// Uses the SDF generated by the SDFShader parameter to create the triangles. The rendering device
    /// passed must be the same one that is used for rendering the triangles.
    /// </summary>
    /// <param name="rd"></param>
    /// <param name="descriptor"></param>
    public TransvoxelTerrainGenerator(RenderingDevice rd, TransvoxelTerrainGeneratorDescriptor descriptor)
    {
        Rd = rd;

        if (descriptor == null)
        {
            throw new ArgumentNullException("Descriptor cannot be null");
        }

        if (descriptor.SDFPipeline == null)
        {
            throw new ArgumentNullException("SDFPipeline cannot be null");
        }

         SdfPipeline = descriptor.SDFPipeline;

        // Setup normals generator
        NormalsShaderDescriptor normalsDescriptor = new NormalsShaderDescriptor()
        {
            ShaderPath = descriptor.NormalsShaderPath,
            ChunkSize = descriptor.ChunkSize, // These are used to allocate the normals buffer
            Lod = descriptor.Lod
        };
        NormalsShader = new NormalsShader.NormalsShader(Rd, normalsDescriptor);

        BorderWidth = descriptor.BorderWidth;
        MaxNumVertices = descriptor.MaxNumVertices;

        // Setup transvoxel
        TransvoxelShaderDescriptor transvoxelShaderDescriptor = new TransvoxelShaderDescriptor()
        {
            ShaderPath = descriptor.TransvoxelShaderPath
        };

        IndirectArgsShaderDescriptor indirectArgsShaderDescriptor = new IndirectArgsShaderDescriptor()
        {
            ShaderPath = descriptor.IndirectArgsShaderPath,
        };

        TransvoxelDescriptor transvoxelDescriptor = new TransvoxelDescriptor()
        {
            TransvoxelShaderDescriptor = transvoxelShaderDescriptor,
            IndirectArgsShaderDescriptor = indirectArgsShaderDescriptor,
            MaxNumTerrainMeshesInQueue = descriptor.MaxNumTerrainMeshesInQueue,
        };

        Transvoxel = new Transvoxel(rd, transvoxelDescriptor);
    }

    /// <summary>
    /// Sets the TransvoxelShaderParamters
    /// </summary>
    /// <param name="transvoxelShaderParameters"></param>
    private void SetTransvoxelShaderConstantParameters(ref TransvoxelShaderParameters transvoxelShaderParameters)
    {
        transvoxelShaderParameters.BorderWidth = BorderWidth; // These are constant
        transvoxelShaderParameters.MaxNumVertices = MaxNumVertices; // These are constant
    }

    /// <summary>
    /// Gets terrain mesh given the current sdf, normal, and transvoxel shader parameters.
    /// Make sure to update the shader parameters using their respective functions if necessary.
    /// If you want to generate a different terrain, it's best to make a new instance of this
    /// object with a different SDFShader.
    /// </summary>
    /// <returns></returns>
    public TerrainMesh GetTerrainMesh(SDFShaderParameters sdfShaderParameters, NormalsShaderParameters normalsShaderParameters, TransvoxelShaderParameters transvoxelShaderParameters)
    {
        RDUniform sdfBufferUniform = SdfPipeline.GetSDF(sdfShaderParameters);
        RDUniform normalsBufferUniform = NormalsShader.Dispatch(normalsShaderParameters, sdfBufferUniform);

        SetTransvoxelShaderConstantParameters(ref transvoxelShaderParameters);

        return Transvoxel.GetTerrainMesh(transvoxelShaderParameters, sdfBufferUniform, normalsBufferUniform);
    }

    /// <summary>
    /// Returns the terrain mesh back to the pool
    /// </summary>
    /// <param name="terrainChunk"></param>
    public void ReturnTerrainMesh(TerrainMesh terrainMesh)
    {
        Transvoxel.ReturnTerrainMesh(terrainMesh);
    }

    public void Dispose()
    {
        SdfPipeline.Dispose();
        NormalsShader.Dispose();
        Transvoxel.Dispose();
    }
}
