using Godot;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TerrainGeneration.Application.SDFGenerator;
using TerrainGeneration.Application.SDFGenerator.Abstractions;
using TerrainGeneration.Application.SDFGenerator.SimplexNoise;
using TerrainGeneration.Application.TerrainGenerator.Transvoxel.NormalsShader;

namespace TerrainGeneration.Application.TerrainGenerator.Transvoxel;
public class TransvoxelTerrainGenerator
{
    RenderingDevice Rd;

    SDFGenerator.SDFGenerator SDFGenerator;
    SDFShaderParameters SDFShaderParameters;

    NormalsShader.NormalsShader NormalsShader;
    NormalsShaderParameters NormalsShaderParameters;

    Transvoxel Transvoxel;
    TransvoxelShaderParameters TransvoxelShaderParameters;

    /// <summary>
    /// Creates a Transvoxel Terrain Generator instance. This uses the transvoxel meshing algorithm.
    /// Uses the SDF generated by the SDFShader parameter to create the triangles. The rendering device
    /// passed must be the same one that is used for rendering the triangles.
    /// </summary>
    /// <param name="rd"></param>
    /// <param name="descriptor"></param>
    public TransvoxelTerrainGenerator(RenderingDevice rd, TransvoxelTerrainGeneratorDescriptor descriptor)
    {
        Rd = rd;

        // Setup sdfGenerator
        //ISDFShader sdfShader = descriptor.SDFShader;
        //SDFShaderParameters = new SDFShaderParameters(descriptor.ChunkOffset, descriptor.ChunkSize, descriptor.Lod);

        //SDFGeneratorSettings sDFGeneratorSettings = new SDFGeneratorSettings()
        //{
        //    SDFShader = sdfShader,
        //    SDFShaderParameters = SDFShaderParameters,
        //};
        //SDFGenerator = new Application.SDFGenerator.SDFGenerator(rd, sDFGeneratorSettings);
        SDFGenerator = null;


        // Setup normals generator
        NormalsShaderParameters = new NormalsShaderParameters(descriptor.ChunkOffset, descriptor.ChunkSize, descriptor.Lod);
        NormalsShaderDescriptor normalsDescriptor = new NormalsShaderDescriptor()
        {
            Parameters = NormalsShaderParameters,
            ShaderPath = descriptor.NormalsShaderPath,
        };
        NormalsShader = new NormalsShader.NormalsShader(Rd, normalsDescriptor);

        TransvoxelShaderParameters = new TransvoxelShaderParameters()
        {
            ChunkSize = descriptor.ChunkSize,
            Lod = descriptor.Lod,
            BorderWidth = descriptor.TransitionWidth,
            MaxNumVertices = descriptor.MaxNumVertices,
        };

        // Setup transvoxel
        TransvoxelShaderDescriptor transvoxelShaderDescriptor = new TransvoxelShaderDescriptor()
        {
            Parameters = TransvoxelShaderParameters,
            ShaderPath = descriptor.TransvoxelShaderPath
        };

        IndirectArgsShaderDescriptor indirectArgsShaderDescriptor = new IndirectArgsShaderDescriptor()
        {
            ShaderPath = descriptor.IndirectArgsShaderPath,
        };

        TransvoxelDescriptor transvoxelDescriptor = new TransvoxelDescriptor()
        {
            TransvoxelShaderDescriptor = transvoxelShaderDescriptor,
            IndirectArgsShaderDescriptor = indirectArgsShaderDescriptor,
            MaxNumTerrainMeshesInQueue = descriptor.MaxNumTerrainMeshesInQueue,
        };

        Transvoxel = new Transvoxel(rd, transvoxelDescriptor);
    }

    /// <summary>
    /// Sets the NormalsShaderParameters
    /// </summary>
    /// <param name="newNormalsShaderParameters"></param>
    public void SetNormalsShaderParameters(NormalsShaderParameters newNormalsShaderParameters)
    {
        NormalsShaderParameters = newNormalsShaderParameters;
    }

    /// <summary>
    /// Sets the NormalsShaderParameters
    /// </summary>
    /// <param name="newSDFShaderParameters"></param>
    public void SetSDFShaderParameters(SDFShaderParameters newSDFShaderParameters)
    {
        SDFShaderParameters = newSDFShaderParameters;
    }

    /// <summary>
    /// Sets the TransvoxelShaderParamters
    /// </summary>
    /// <param name="transvoxelShaderParameters"></param>
    public void SetTransvoxelShaderParameters(TransvoxelShaderParameters transvoxelShaderParameters)
    {
        transvoxelShaderParameters.BorderWidth = TransvoxelShaderParameters.BorderWidth; // These are constant
        transvoxelShaderParameters.MaxNumVertices = TransvoxelShaderParameters.MaxNumVertices; // These are constant

        TransvoxelShaderParameters = transvoxelShaderParameters;
    }

    /// <summary>
    /// Gets terrain mesh given the current sdf, normal, and transvoxel shader parameters.
    /// Make sure to update the shader parameters using their respective functions if necessary.
    /// If you want to generate a different terrain, it's best to make a new instance of this
    /// object with a different SDFShader.
    /// </summary>
    /// <returns></returns>
    public TerrainMesh GetTerrainMesh()
    {
        SDFGenerator.DispatchShaders(SDFShaderParameters);
        RDUniform sdfBufferUniform = SDFGenerator.OutputBufferUniform;

        NormalsShader.Dispatch(NormalsShaderParameters, sdfBufferUniform);
        RDUniform normalsBufferUniform = NormalsShader.OutputNormalsUniform;

        return Transvoxel.GetTerrainMesh(TransvoxelShaderParameters, sdfBufferUniform, normalsBufferUniform);
    }

    /// <summary>
    /// Returns the terrain mesh back to the pool
    /// </summary>
    /// <param name="terrainChunk"></param>
    public void ReturnTerrainMesh(TerrainMesh terrainMesh)
    {
        Transvoxel.ReturnTerrainMesh(terrainMesh);
    }

    public void Dispose()
    {
        SDFGenerator.Dispose();
        NormalsShader.Dispose();
        Transvoxel.Dispose();
    }
}
